### PR TITLE
Added Makefile

### PR DESCRIPTION
**Pull request by surajnarwade**
This PR will add makefile which will add basic operations like validation,
build, install etc.

### CODE REVIEW

**Comment by surajnarwade** [comment]
Resolves https://github.com/kubernauts/tk8/issues/11

**Comment by arush-sal** [comment]
@surajnarwade Cloud you please sign your commit and add sign-off.

**Comment by surajnarwade** [comment]
@arush-sal added :)

**Comment by surajnarwade** [comment]
@arush-sal good to merge :)

**Pull request merged**
